# Generated by Django 6.0.3 on 2026-03-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('project', 'external_id'), name='unique_place_per_project'),
        ),
    ]
